Repository vatpac-technology/sops, pull requests merged in 2025-04, with the labels that each got.

#488 Fix navbar using full height on WebKit browsers
  docs/stylesheets/navigation.css
Labels: notify, cosmetic

#510 Header/Paragraph Indentation
  docs/enroute/Melbourne Centre/BLA.md
  docs/javascripts/table-indent.js
  docs/stylesheets/admonitions.css
  docs/stylesheets/extra.css
  mkdocs.yml
Labels: cosmetic

#514 Adjust HYD(GEL) STAR expectation, Essendon Typo fix
  docs/aerodromes/classc/Essendon.md
  docs/enroute/Melbourne Centre/HYD.md
  docs/oceanic/Positions/IND.md
Labels: fix

#507 PNG Aerodrome ATIS frequency updates
  docs/pacific/Papua-New-Guinea/Enroute.md
  docs/pacific/Papua-New-Guinea/Mt-Hagen.md
  docs/pacific/Papua-New-Guinea/Nadzab.md
  docs/pacific/Papua-New-Guinea/Tokua.md
Labels: notify, DO NOT MERGE

#518 Add/Expand Port Vila SOPs
  docs/pacific/Vanuatu/Enroute.md
  docs/pacific/Vanuatu/Port-Vila.md
  docs/pacific/Vanuatu/img/NVVVCTR.png
  docs/pacific/Vanuatu/img/NVVVTWR.png
  docs/pacific/Vanuatu/img/NVVV_trainingarea.png
  docs/pacific/Vanuatu/img/nvvv_rwy11.png
  docs/pacific/Vanuatu/index.md
  docs/pacific/assets/pacificairspace.png
  docs/pacific/index.md
  includes/abbreviations.md
Labels: new procedures, notify

#524 Fix reference to ADC 2 -> ADC S Tamworth
  docs/aerodromes/procedural/Tamworth.md
Labels: fix

#522 Add/Expand AYPM, Nadzab, Class F SOPs
  docs/pacific/Papua-New-Guinea/Class F/Goroka.md
  docs/pacific/Papua-New-Guinea/Class F/Madang.md
  docs/pacific/Papua-New-Guinea/Class F/Mt-Hagen.md
  docs/pacific/Papua-New-Guinea/Class F/Tokua.md
  docs/pacific/Papua-New-Guinea/Enroute.md
  docs/pacific/Papua-New-Guinea/Goroka.md
  docs/pacific/Papua-New-Guinea/Madang.md
  docs/pacific/Papua-New-Guinea/Mt-Hagen.md
  docs/pacific/Papua-New-Guinea/Nadzab (AYNZ)/AD.md
  docs/pacific/Papua-New-Guinea/Nadzab (AYNZ)/TCU.md
  docs/pacific/Papua-New-Guinea/Nadzab.md
  docs/pacific/Papua-New-Guinea/Tokua.md
  docs/pacific/Papua-New-Guinea/img/AYNZ_ADC.png
  docs/pacific/Papua-New-Guinea/img/AYNZ_TMA.png
  docs/pacific/Papua-New-Guinea/img/aynz_markham_river.png
Labels: new procedures, notify
