Repository vatpac-technology/sops, pull requests merged in 2025-09, with the labels that each got.

#599 Handling Military Aircraft
  docs/controller-skills/military.md
Labels: notify

#604 Update SNO freq
  docs/enroute/Melbourne Centre/ASP.md
  docs/enroute/Melbourne Centre/WOL.md
Labels: airac, ais

#602 Controller Skills - 'Extending' remarks now automatic with VATPAC plugin
  docs/controller-skills/extending.md
Labels: notify, DO NOT MERGE, airac, change

#596 Perth CDO Timings Update
  docs/enroute/Melbourne Centre/HYD.md
Labels: notify, DO NOT MERGE, airac, ais

#606 Add RRSM operations and map details
  docs/aerodromes/classc/Brisbane.md
  docs/aerodromes/classc/Melbourne.md
  docs/aerodromes/classc/Perth.md
  docs/aerodromes/classc/Sydney.md
  docs/separation-standards/runway.md
Labels: notify, airac

#610 .pages fix
  docs/pacific/New-Caledonia/.pages
  docs/pacific/Vanuatu/.pages
Labels: fix

#598 YMEN VFR Outbound Points
  docs/aerodromes/classc/Essendon.md
  docs/terminal/melbourne.md
  includes/abbreviations.md
Labels: notify

#591 Pilot Procedures Changes, Traffic Info Plugin
  docs/aerodromes/classc/Richmond.md
  docs/aerodromes/classc/Sydney.md
  docs/aerodromes/classc/img/yssy_apron_routes.png
  docs/assets/archived_hero_images/archived_2025-08-31.png
  docs/assets/hero-image.png
  docs/client/trafficinfo.md
  docs/controller-skills/img/dticreate.png
  docs/controller-skills/img/dtidelete.png
  docs/controller-skills/img/dtioverview.png
  docs/controller-skills/img/dtirecord.png
  docs/enroute/Brisbane Centre/ARL.md
  docs/enroute/Melbourne Centre/BLA.md
  docs/enroute/Melbourne Centre/HYD.md
  docs/enroute/Melbourne Centre/MUN.md
  docs/events/milkrun/aerodrome.md
  docs/javascripts/table-indent.js
  docs/oceanic/procedures.md
  docs/terminal/img/sytcu_wsiappx.png
  docs/terminal/perth.md
  docs/terminal/sydney.md
  overrides/assets/stylesheets/home.css
Labels: notify

#617 Update Sydney Aerodrome Diagrams
  docs/aerodromes/classc/Sydney.md
  docs/aerodromes/classc/img/yssy_apron_routes.png
  docs/aerodromes/classc/img/yssy_apron_routes_arrivals.png
  docs/aerodromes/classc/img/yssy_apron_routes_departures.png
  docs/aerodromes/classc/img/yssy_taxi_routes.png
  docs/aerodromes/classc/img/yssymaown.png
Labels: notify

#621 Fix outdated images: ARL/INL and BN TCU
  docs/enroute/assets/arl.png
  docs/enroute/assets/inl.png
  docs/terminal/img/bn01props.png
  docs/terminal/img/bn19props.png
  docs/terminal/img/bnsodprops.png
Labels: fix

#625 Fix broken links to pushback requests on acd page
  docs/aerodromes/classc/Brisbane.md
  docs/aerodromes/classc/Melbourne.md
  docs/aerodromes/classc/Perth.md
Labels: fix
