Repository vatpac-technology/sops, pull requests merged in 2025-07, with the labels that each got.

#446 Bucholz AAF (PKWA) SOP Update
  docs/pacific/Marshall-Islands/Kwajalein.md
  docs/pacific/Marshall-Islands/index.md
Labels: notify, DO NOT MERGE

#560 Papua New Guinea VFR + Heli Ops Details
  docs/pacific/Papua-New-Guinea/Nadzab/AD.md
  docs/pacific/Papua-New-Guinea/Port-Moresby/AD.md
  docs/pacific/Papua-New-Guinea/classf/Goroka.md
  docs/pacific/Papua-New-Guinea/classf/Mt-Hagen.md
  docs/pacific/Papua-New-Guinea/img/ayd903-907.png
  docs/pacific/Papua-New-Guinea/img/ayga_vfr.png
  docs/pacific/Papua-New-Guinea/img/aymh_helipads.png
  docs/pacific/Papua-New-Guinea/img/aymh_vfr.png
  docs/pacific/Papua-New-Guinea/img/aynz_vfr.png
  docs/pacific/Papua-New-Guinea/img/aypy_vfr.png
Labels: notify, ais, low priority

#551 Add/Expand Fiji SOPs
  docs/pacific/Fiji/.pages
  docs/pacific/Fiji/Enroute.md
  docs/pacific/Fiji/Nadi.md
  docs/pacific/Fiji/Nadi/.pages
  docs/pacific/Fiji/Nadi/AD.md
  docs/pacific/Fiji/Nadi/TCU.md
  docs/pacific/Fiji/Nausori.md
  docs/pacific/Fiji/Nausori/.pages
  docs/pacific/Fiji/Nausori/AD.md
  docs/pacific/Fiji/Nausori/TCU.md
  docs/pacific/Fiji/Oceanic.md
  docs/pacific/Fiji/img/fjpdz2.png
  docs/pacific/Fiji/img/nfff.png
  docs/pacific/Fiji/img/nffn_02a20d_conflicts.png
  docs/pacific/Fiji/img/nffn_adc.png
  docs/pacific/Fiji/img/nffn_ctr.png
  docs/pacific/Fiji/img/nffn_denarau_island.png
  docs/pacific/Fiji/img/nffn_helipads.png
  docs/pacific/Fiji/img/nffn_tcu.png
  docs/pacific/Fiji/img/nffn_tiliva.png
  docs/pacific/Fiji/img/nffn_vfr.png
  docs/pacific/Fiji/img/nffnsmc.png
  docs/pacific/Fiji/img/nfna_adc.png
  docs/pacific/Fiji/img/nfna_namuka.png
  docs/pacific/Fiji/img/nfna_tcu.png
  docs/pacific/Fiji/img/nfna_vfr.png
  docs/pacific/New-Caledonia/Enroute.md
  docs/pacific/New-Caledonia/index.md
  docs/pacific/Papua-New-Guinea/Nadzab/AD.md
  docs/pacific/Solomon-Islands/index.md
  docs/pacific/Vanuatu/Port-Vila.md
  includes/abbreviations.md
Labels: new procedures, notify, ais

#573 Update Handoff Requirement during SODPROPS
  docs/terminal/brisbane.md
  docs/terminal/sydney.md
Labels: notify

#574 Perth SID Selection Update
  docs/aerodromes/classc/Perth.md
Labels: notify

#566 Brisbane Noise Abatement Runway Mode Adjustments
  docs/aerodromes/classc/Brisbane.md
Labels: notify

#578 Add missing GIG_GND position
  docs/aerodromes/classc/Gingin.md
Labels: fix

#418 Stereo Approaches
  docs/controller-skills/military.md
  docs/terminal/tindal.md
  docs/terminal/williamtown.md
Labels: notify
