Repository vatpac-technology/sops, pull requests merged in 2025-06, with the labels that each got.

#534 Add/Expand New Caledonia, ANAU/AGGG SOPs
  docs/pacific/Nauru/.pages
  docs/pacific/Nauru/img/ANAU.png
  docs/pacific/Nauru/img/ANAU_airspace.png
  docs/pacific/Nauru/index.md
  docs/pacific/New-Caledonia/.pages
  docs/pacific/New-Caledonia/Enroute.md
  docs/pacific/New-Caledonia/La-Tontouta.md
  docs/pacific/New-Caledonia/Magenta.md
  docs/pacific/New-Caledonia/TCU.md
  docs/pacific/New-Caledonia/img/new_caledonia_vfr_points.png
  docs/pacific/New-Caledonia/img/nwwm_17_circling.png
  docs/pacific/New-Caledonia/img/nwwm_adc.png
  docs/pacific/New-Caledonia/img/nwwm_vfr_night.png
  docs/pacific/New-Caledonia/img/nwww_29_circling.png
  docs/pacific/New-Caledonia/img/nwww_adc.png
  docs/pacific/New-Caledonia/img/nwww_ctr.png
  docs/pacific/New-Caledonia/img/nwww_tcu.png
  docs/pacific/New-Caledonia/img/nwww_vfr_night.png
  docs/pacific/New-Caledonia/index.md
  docs/pacific/Papua-New-Guinea/Enroute.md
  docs/pacific/Papua-New-Guinea/Nadzab/TCU.md
  docs/pacific/Papua-New-Guinea/Port-Moresby/TCU.md
  docs/pacific/Solomon-Islands/.pages
  docs/pacific/Solomon-Islands/img/AGGG.png
  docs/pacific/Solomon-Islands/img/AGGG_airspace.png
  docs/pacific/Solomon-Islands/index.md
  docs/pacific/Vanuatu/Enroute.md
  docs/pacific/Vanuatu/Port-Vila.md
  docs/pacific/Vanuatu/img/NVVVCTR.png
  docs/pacific/assets/pacificairspace.png
  includes/abbreviations.md
Labels: new procedures, notify, ais, low priority

#549 AYPY Formatting and Minor Adjustments
  docs/pacific/Papua-New-Guinea/Nadzab/TCU.md
  docs/pacific/Papua-New-Guinea/Port-Moresby/AD.md
  docs/pacific/Papua-New-Guinea/Port-Moresby/TCU.md
  docs/pacific/Papua-New-Guinea/img/aypy_helipads.png
  docs/pacific/Papua-New-Guinea/img/aypy_rtcc.png
Labels: notify

#550 Change home.css fix three column on small screen
  overrides/assets/stylesheets/home.css
Labels: cosmetic

#553 Fix Tokua ATIS freq
  docs/pacific/Papua-New-Guinea/classf/Tokua.md
Labels: fix

#556 YSSY ATIS Freq & Linkair Callsign
  docs/aerodromes/classc/Sydney.md
  docs/controller-skills/callsigns.md
Labels: notify, change

#558 'Standby for Ground' Phraseology Update
  docs/aerodromes/classc/Brisbane.md
  docs/aerodromes/classc/Melbourne.md
  docs/aerodromes/classc/Perth.md
  docs/aerodromes/classc/Sydney.md
  docs/aerodromes/classc/img/coordinator-ozstrips.png
  docs/client/towerstrips.md
  docs/controller-skills/grounddelaymanagement.md
  docs/controller-skills/img/ozstripscoordinator.png
  docs/events/milkrun/workload.md
Labels: notify, change
